### ISSUE TITLE
datepicker `change` event fired twice.

### ISSUE THREAD

**Issue by kntmrkm** [eternicode/bootstrap-datepicker#1233]
When 'change' event set to datepicker field.

'change' event fire twice.

In repo [vizjerai/bootstrap-datepicker](https://github.com/vizjerai/bootstrap-datepicker/).

This issue is fixed like this.

[Fix multiple calls to change #4](https://github.com/vizjerai/bootstrap-datepicker/issues/4)
[commit](https://github.com/vizjerai/bootstrap-datepicker/commit/db20cae1d6ada09c9693fb780567388508b3ff57)

How is going at this repo?

This fixing is correct?

**Comment by acrobat** [comment]
Yes I saw that patch before, I'm going to look at that issue soon and see if the patch is correct!

**Comment by kntmrkm** [comment]
OK. Thanks.

**Comment by mgodwin** [comment]
:+1:

**Comment by acrobat** [comment]
Fixed in #1337

**Comment by akhayoon** [comment]
Does this mean the issue was fixed in 1.5.0? 

This is because I'm using 1.6.0 and I'm still getting the event triggered 3 times on the 'change dp.change' event. Please advise if I'm doing something wrong. Thank you

**Comment by seanjamu** [comment]
this problem persist now in range datepicker, when select date in a input it cause two events

**Comment by vqminh** [comment]
Still see this on 1.6.1

**Comment by acrobat** [comment]
Can you guys provide a jsfiddle to show if the problem still persists? It should be fixed with the pr, but maybe some new code broke it against

**Comment by yassirtaqatqa** [comment]
Just change it to...
`.on('changeDate',function() {
                    do_staff();
                });`

**Comment by mistrynilesh** [comment]
I am using 1.6.4.  Still facing same issue in version on 1.6.4.

**Comment by roysupriya** [comment]
In my case, I am using daterangepicker with angular. My purpose is to watch any change in the model that stores the date range value and save it for an AJAX call later. I face the same issue as it hits the event twice whenever the date is change even if it is only 'Today': **_Once it is object with startDate and endDate properties, and the other time it is a string._**

**It can be made use of as an advantage.**    
```
$scope.$watch(
    'rangeOfDate',
    function (newValue) {
        // Due to a known bug of open source library daterangepicker, the event is hit twice 
        //upon change. Once it is an object, and once it is a string. So, use appropriately.
        var selectedDateRange = new Object();
        if (typeof (newValue) == 'object') {
            selectedDateRange.startDate = new Date(newValue.startDate).toLocaleDateString();
            selectedDateRange.endDate = new Date(newValue.endDate).toLocaleDateString();
            //Do as you wish with this custom object
        }
        else if (typeof (newValue) == 'string') {
            alert("string");
        }               
    },
    false);


```
