### ISSUE TITLE
Disabled dates getting selected on "ENTER" key press

### ISSUE THREAD

**Issue by medigvijay** [eternicode/bootstrap-datepicker#1877]
I have disabled few dates in the date-picker but while navigating with keyboard to a disabled date and pressing ENTER key the disabled date gets selected on "ENTER" key press.
Can be tested on this page

https://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=2&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&daysOfWeekDisabled=1&daysOfWeekDisabled=2&keyboardNavigation=on&forceParse=on#sandbox

Thanks

**Comment by medigvijay** [comment]
Here is what I have done to fix it at line **1288** for the **case 13**:

`if(this.o.daysOfWeekDisabled.indexOf(focusDate.getDay()) !== -1) {						 

    e.preventDefault();

    if (typeof e.stopPropagation === 'function') {

	e.stopPropagation(); // All modern browsers, IE9+

    } else {

	e.cancelBubble = true; // IE6,7,8 ignore "stopPropagation"

    }

    return false;

}`

Please let me know if this is the right way to do it.
Thanks

**Comment by Azaret** [comment]
This issue have been fixed in the latest version.
Thank you for your feedback.

**Comment by medigvijay** [comment]
But I am still facing the same issue in the [demo page](https://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=2&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&daysOfWeekDisabled=0&daysOfWeekDisabled=1&keyboardNavigation=on&forceParse=on#sandbox)

**Comment by acrobat** [comment]
@medigvijay the demo page js versie is still out dated, I will try to update it as soon as possible

**Comment by acrobat** [comment]
Js and css have been updated on the demo page

**Comment by medigvijay** [comment]
Thanks working now
