### ISSUE TITLE
Using jQuery .change loops 3 times

### ISSUE THREAD

**Issue by PierceMcGeough** [eternicode/bootstrap-datepicker#927]
When using the $('#id').change() function it seems to loop through 3 times every time. Is there a fix for this or why does it happen?

**Comment by acrobat** [comment]
Fixed in #1337

**Comment by samuelstein** [comment]
i tried the latest release and the bug still persists. what i'm doing wrong?
